BEGIN TRANSACTION;
CREATE TABLE Type(id INTEGER PRIMARY KEY, ord INTEGER, type TEXT, nvar INTEGER, open BOOLEAN);
CREATE TABLE Sequence(id INTEGER PRIMARY KEY, a1 TEXT, a2 TEXT, a3 TEXT, a4 TEXT, paf BOOLEAN, npaf BOOLEAN);
CREATE TABLE Source(id INTEGER PRIMARY KEY, sid INTEGER, method TEXT, ref TEXT, FOREIGN KEY(sid) REFERENCES Sequence(id));
CREATE TABLE Witness(id INTEGER PRIMARY KEY, tid INTEGER, sid INTEGER, paf_normal, npaf_normal, FOREIGN KEY(tid) REFERENCES Type(id), FOREIGN KEY(sid) REFERENCES Sequence(id));
COMMIT;
